[package]
name = "server_manager_gui"
version.workspace = true
edition.workspace = true

[dependencies]
slint = "1.10"
anyhow.workspace = true

[build-dependencies]
slint-build = "1.10"
anyhow.workspace = true
