[workspace]
members = [
    "server",
    "server/migration",
    "server/derive",
    "server/server_manager",
    "server/base",
    "server/load_balancer",
    "server/client",
    "server/stress_test",
    "server/registry",
    "server/entities",
    "server/pb",
    "server/consul-client",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
strip = true

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[workspace.dependencies]
tokio = { version = "1", features = ["full", "tracing"] }
bytes = "1"
anyhow = "1"
serde = { version = "1" }
serde_json = "1"
# serde_repr = "0"
# tokio-tungstenite = "0"
clap = { version = "4", features = ["derive"] }
futures-util = "0"
rand = "0"
snowdon = "0"

thiserror = "2"
chrono = { version = "0", features = ["serde"] }
base = { path = "base" }
tracing = { version = "0" }
tracing-appender = "0"
tracing-subscriber = { version = "0", features = ["tracing-log", "env-filter"] }
migration = { path = "migration" }
mimalloc = "0"
parking_lot = "0"
derive = { path = "derive" }
dashmap = { "version" = "6" }
sha3 = "0"
config = "0"
validator = "0"
argon2 = { version = "0", features = ["std"] }
deadpool-redis = "0.18.0"
console-subscriber = { version = "0", features = ["parking_lot"] }
consul-client = { path = "consul-client" }
registry = { path = "registry" }
ring = "0"

# Useful crates
collection_literals = "1"
colored = "2"
strum = { version = "0", features = ["derive"] }
size = { version = "0.5.0-preview2", features = ["serde"] }

# num_enum = "0"
mockall = "0"
async-trait = { version = "0" }
# serde_plain = "1"

# Grpc
tonic-types = { version = "0" }
prost-types = { version = "0" }
prost = { version = "0" }
jsonwebtoken = "9"
tokio-stream = { version = "0" }

# Protobuf definitions
pb = { path = "pb" }

entities = { path = "entities" }

linkify = "0"
claims = "0"

[workspace.dependencies.lettre]
version = "0"
default-features = false
features = ["tokio1", "tokio1-rustls-tls", "smtp-transport", "builder"]

[workspace.dependencies.reqwest]
version = "0"
default-features = false
features = ["json", "rustls-tls"]

[workspace.dependencies.redis]
version = "0"
default-features = false
features = ["tokio-rustls-comp"]

[workspace.dependencies.tonic]
version = "0"
default-features = false
features = ["tls"]

[workspace.dependencies.sqlx]
version = "0"
default-features = false
features = ["runtime-tokio-rustls", "migrate"]

[workspace.dependencies.sea-orm]
version = "1"
default-features = false
features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "with-json",
    "with-chrono",
]

[workspace.dependencies.actix-web]
version = "4"
default-features = false
features = ["rustls", "macros"]

[workspace.dependencies.uuid]
version = "1"
default-features = false
features = ["v4", "serde"]
