[workspace]
members = [
    "server",
    "server/migration",
    "server/derive",
    "server/server_manager",
    "server/base",
    "server/load_balancer",
    "server/client",
    "server/stress_test",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
strip = true

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
