[workspace]
members = [
    "server",
    "server/test_lib",
    "client/src-tauri",
    "client/web",
    "client/web/derive",
    "client/pc/src/rmodule",
    "base",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
strip = true

[workspace.package]
version = "0.1.0"
