name: ourchat_server_prod
services:
  OurChatServer:
    build:
      context: .
      dockerfile: Dockerfile.prod
    init: true
    image: ourchat_prod:latest
    volumes:
      - "/dev:/dev:rw"
      - .:/app
    working_dir: /root
    environment:
      - LC_ALL=C.UTF-8
    ports:
      - "7777:7777"
    networks:
      - net
  db:
    image: mysql:9.0.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: OurChat
    volumes:
      - "./data/mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - net
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/opt/redis/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=123456
    networks:
      - net

networks:
  net:
    driver: bridge
