name: ourchat_server
services:
  OurChatServer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    init: true
    image: ourchat_develop:latest
    command: tail -f /dev/null
    volumes:
      - "/dev:/dev:rw"
      - .:/app
    working_dir: /root
    environment:
      - LC_ALL=C.UTF-8
    ports:
      - "7777:7777"
      - "7778:7778"
    networks:
      - net
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - "./data/postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - net
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/opt/redis/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - net

networks:
  net:
    driver: bridge
