name: ourchat_server
services:
  OurChatServer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    init: true
    container_name: OurChatServer
    network_mode: "host"
    image: ourchat_develop:latest
    command: tail -f /dev/null
    volumes:
      - "/dev:/dev:rw"
      - .:/app
    working_dir: /root
    environment:
      - LC_ALL=C.UTF-8
  db:
    image: mysql:9.0.1
    restart: always
    # network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: OurChat
    volumes:
      - "./mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/opt/redis/data
    environment:
      - REDIS_PASSWORD=123456
