# Ip listening
ip = "127.0.0.1"
# Assign the config file of database,relative to this config file
dbcfg = "database.toml"
# Assign the config file of redis database,relative to this config file
rediscfg = "redis_connect.toml"
# Ourchat Listening Port
port = 7777
# The http server listening port
http_port = 7778
# The duration of cleaning the files which are out-of-date
auto_clean_duration = 1
# The total file size limit of single user
user_files_limit = "100MiB"
# The friends number limit of single user
friends_number_limit = 5000
# Whether enabling the terminal
enable_cmd = true
# Whether enabling the stdin source of the terminal
enable_cmd_stdin = true
# Assign the network terminal listening port,note,it will enable the network terminal mode by default
cmd_network_port = 7779
# The expire time in days of the verification request
verification_expire_days = 3
# The path of the users' files storage
files_storage_path = "files_storage/"
# Enable ssl encryption
ssl = false
# Whether this is started in Single Instance Mode. If true, some actions like cleaning up files will be performed regularly
# You can set it when you have only one server instance, or you can set this option in only one instance(not recommended)
single_instance = true

[password_hash]
# The memory size in 1 KiB blocks. Between 8*`p_cost` and (2^32)-1
m_cost = 19456
# The number of iterations. Between 1 and (2^32)-1
t_cost = 2
# The degree of parallelism. Between 1 and (2^24)-1
p_cost = 1
# The size of the KDF output in bytes
output_len = 32

[db]
# The size of one page to fetch message
fetch_msg_page_size = 2000

[debug]
debug_console = true
# Warning: don't expose it to the world
debug_console_port = 7776

# Registry Centre of Services
[registry]
# Whether to add this service to registry
enable = false
# Registry address
ip = "127.0.0.1"
# Registry port
port = 8500
# Registry service name
service_name = "RpcServer"

# If any fields below is not specified, the email will be disabled
[email]
# Whether to enable email service
enable = false
# Email address displaying in sent email
email_address = "default@ourchat.org"
# Smtp server address
smtp_address = "smtp.ourchat.org"
# Smtp server password
smtp_password = "password"
