# The http server listening ip
ip = "0.0.0.0"
# The http server listening port
port = 7778
redis_cfg = "redis.toml"
db_cfg = "database.toml"
user_setting = "user_setting.toml"
# If not set, the email will be disabled
email_cfg = "email.toml"
rabbitmq_cfg = "rabbitmq.toml"
# The logo of this server
logo_path = "../resource/logo.png"
run_migration = false
# Log clean duration
log_clean_duration = "30d"
# Keep Log Duration when cleaning
log_keep = "3d"

[tls]
enable = false
