# Ip listening
ip = "0.0.0.0"
# Assign the config file of a database, relative to this config file
db_cfg = "database.toml"
# Assign the config file of a redis database, relative to this config file
redis_cfg = "redis.toml"
# Assign the config file of a rabbitmq, relative to this config file
rabbitmq_cfg = "rabbitmq.toml"
user_setting = "user_setting.toml"
# Ourchat Listening Port
port = 7777
# Just for showing, will not use this port
http_port = 7778
# The duration of cleaning the files which are out-of-date
auto_clean_duration = "0 0 * * *"
# The total file size limit of a single user
user_files_limit = "100MiB"
# A single user's The number of the friend's limit
friends_number_limit = 5000
# The expiry time in days of the verification request
verification_expire_time = "3d"
# The expiry time in hours of the user defined status
user_defined_status_expire_time = "24h"
# The path of the users' files storage
files_storage_path = "files_storage/"
# How long will the files be kept
files_save_time = "10d"
# Whether this is started in Single Instance Mode. If true, some actions like cleaning up files will be performed regularly
# You can set it when you have only one server instance, or you can set this option in only one instance(not recommended)
single_instance = true
# In multiple instance mode, choose a node to be the leader node
leader_node = true
# Log clean duration
log_clean_duration = "30d"
# Keep Log Duration when cleaning
log_keep = "3d"

[password_hash]
# The memory size in 1 KiB blocks. Between 8*`p_cost` and (2^32)-1
m_cost = 19456
# The number of iterations. Between 1 and (2^32)-1
t_cost = 2
# The degree of parallelism. Between 1 and (2^24)-1
p_cost = 1
# The size of the KDF output in bytes
output_len = 32

[db]
# The size of one page to fetch a message
fetch_msg_page_size = 2000

[debug]
debug_console = true
# Warning: don't expose it to the world
debug_console_port = 7776

[tls]
# Enable tls encryption
enable = false
client_certificate_required = false
# The address of the tsl certificate, if not specified, the tls will be disabled
# server_tls_cert_path = ""
# server_key_cert_path = ""
# client_tls_cert_path = ""
# client_key_cert_path = ""
# ca_tls_cert_path = ""
# client_ca_tls_cert_path = ""
