[package]
name = "load_balancer"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0"
pingora = { version = "0", features = ["lb", "rustls"] }
base = { path = "../base" }
serde = { version = "1" }
clap = { version = "4", features = ["derive"] }
config = "0"
