[package]
name = "load_balancer"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0"
base = { path = "../base" }
serde = { version = "1" }
clap.workspace = true
config = "0"

[dependencies.pingora]
version = "0"
default-features = false
features = ["lb", "rustls"]
