# Just A Template Should be modified to fit requirement
name: ourchat_server
services:
  OurChatServer:
    init: true
    image: skyuoi/ourchat:latest
    working_dir: /root
    ports:
      - "7777:7777"
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config/:/etc/ourchat
      - ../resource/:/etc/resource
  HttpServer:
    init: true
    image: skyuoi/ourchat:latest-http
    working_dir: /root
    ports:
      - "7778:7778"
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config/:/etc/ourchat
      - ../resource/:/etc/resource
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: OurChat
      POSTGRES_PASSWORD: 123456
    volumes:
      - "./data/postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 5
  garnet:
    image: 'ghcr.io/microsoft/garnet'
    restart: always
    command: GarnetServer --config-import-path /usr/local/etc/garnet/garnet.conf
    ports:
      - "6379:6379"
    volumes:
      - ./data/garnet-data:/data
      - ./config/garnet.conf:/usr/local/etc/garnet/garnet.conf
    networks:
      - net
  mq:
    image: rabbitmq:4-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq-data:/var/lib/rabbitmq
    networks:
      - net

networks:
  net:
    driver: bridge
