# This template can set up an environment for testing or developing
name: ourchat_server
services:
  OurChatServer:
    init: true
    build:
      context: ..
      dockerfile: docker/Dockerfile.test-aphine
    image: test-ourchat-aphine:latest
    environment:
      - OURCHAT_TEST_CONFIG_DIR=/app/config
      - OURCHAT_LOG=trace,actix_web=off,actix_server=off,mio=off,h2=off,tonic=off,tower=off,tokio::task::waker=off,runtime::resource=off,actix_http=off,lapin=off,hyper_util=off,pinky_swear=off,async_io=off,polling=off
    command: tail -f /dev/null
    working_dir: /app
    ports:
      - "7777:7777"
      - "7778:7778"
    networks:
      - net
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: OurChat
      POSTGRES_PASSWORD: 123456
    volumes:
      - "./data/postgres-data:/var/lib/postgresql/data"
      - "./data/postgres-var:/var/run/postgresql"
    ports:
      - "5432:5432"
    networks:
      - net
    user: 1000:1000
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/opt/redis/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - net
    user: 1000:1000
  mq:
    image: rabbitmq:4-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq-data:/var/lib/rabbitmq
    networks:
      - net
    user: 1000:1000

networks:
  net:
    driver: bridge
