# Just A Template Should be modified to fit requirement
name: ourchat_server
services:
  OurChatServer:
    init: true
    image: skyuoi/ourchat:nightly
    working_dir: /root
    ports:
      - "7777:7777"
      - "7779:7779"
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config/:/etc/ourchat
      - ./log:/root/log
      - ../resource/:/etc/resource
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: OurChat
      POSTGRES_PASSWORD: 123456
    volumes:
      - "./data/postgres-data:/var/lib/postgresql/data"
      # If you want to expose the postgres port, uncomment the following lines
      # ports:
      # - "5432:5432"
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
  redis:
    image: redis:8-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    # If you want to expose the redis port, uncomment the following lines
    # ports:
    # - "6379:6379"
    volumes:
      - ./data/redis-data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - net
  mq:
    image: rabbitmq:4-management-alpine
    restart: always
    # If you want to expose the rabbitmq management port, uncomment the following lines
    # ports:
    # - "5672:5672"
    # - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - ./data/rabbitmq-data:/var/lib/rabbitmq
    networks:
      - net

networks:
  net:
    driver: bridge
