# Just A Template Should be modified to fit requirement
name: ourchat_server
services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: OurChat
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      - net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 5
  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - net
  mq:
    image: rabbitmq:4-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net

networks:
  net:
    driver: bridge
