# This template can set up a environment for testing or developing
name: ourchat_server
services:
  OurChatServer:
    build:
      context: .
      dockerfile: ./Dockerfile.dev-debian
    init: true
    image: ourchat_develop:latest
    command: tail -f /dev/null
    volumes:
      - "/dev:/dev:rw"
    working_dir: /root
    ports:
      - "7777:7777"
      - "7778:7778"
    networks:
      - net
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: OurChat
      POSTGRES_PASSWORD: 123456
    volumes:
      - "./data/postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - net
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/opt/redis/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - net

networks:
  net:
    driver: bridge
