# This template can set up an environment for testing or developing
name: ourchat_server_test_debian
services:
  OurChatServer:
    init: true
    build:
      context: ..
      dockerfile: docker/Dockerfile.test-debian
    image: test-ourchat-debian:latest
    environment:
      - OURCHAT_CONFIG_FILE=/app/docker/config/ourchat.toml
      - OURCHAT_LOG=trace,mio=off,h2=off,tonic=off,tower=off,tokio::task::waker=off,runtime::resource=off,actix_http=off,lapin=off,hyper_util=off,pinky_swear=off,async_io=off,polling=off
    command: tail -f /dev/null
    working_dir: /app
    volumes:
      - ../resource/:/app/docker/resource
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: OurChat
      POSTGRES_PASSWORD: 123456
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
  redis:
    image: redis:8
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - net
  mq:
    image: rabbitmq:4-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: 123456
    networks:
      - net

networks:
  net:
    driver: bridge
