[package]
name = "server"
version.workspace = true
edition.workspace = true
rust-version = "1.80"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
anyhow = "1"
serde = { version = "1" }
serde_json = "1"
serde_repr = "0"
tokio-tungstenite = "0"
tungstenite = "0"
sqlx = { version = "0", features = [
    "runtime-tokio",
    "tls-rustls",
    "mysql",
    "macros",
] }
log = "0"
clap = { version = "4", features = ["derive"] }
shadow-rs = "0"
futures-util = "0"
rand = "0"
snowdon = "0"
redis = { version = "0", features = ["tokio-rustls-comp"] }
toml = "0"
sea-orm = { version = "1", features = [
    "sqlx-mysql",
    "runtime-tokio-rustls",
    "macros",
] }
thiserror = "1"
chrono = "0"
num_enum = "0"
base = { path = "../base" }
tracing = { version = "0" }
tracing-appender = "0"
tracing-subscriber = { version = "0", features = ["tracing-log", "env-filter"] }

[build-dependencies]
shadow-rs = "0"

[dev-dependencies]
test_lib = { path = "test_lib" }
serial_test = "3"
