cargo-features = ["edition2024"]
[package]
name = "server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
anyhow = "1"
serde = { version = "1" }
serde_json = "1"
serde_repr = "0"
tokio-tungstenite = "0"
clap = { version = "4", features = ["derive"] }
futures-util = "0"
rand = "0"
snowdon = "0"
redis = { version = "0", features = ["tokio-rustls-comp"] }
sea-orm = { version = "1", features = [
    "sqlx-mysql",
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
] }
thiserror = "1"
chrono = "0"
base = { path = "base" }
tracing = { version = "0" }
tracing-appender = "0"
tracing-subscriber = { version = "0", features = ["tracing-log", "env-filter"] }
migration = { path = "migration" }
mimalloc = "0"
parking_lot = "0"
static-keys = "0"
sqlx = { version = "0", features = ["runtime-tokio-rustls", "sqlite"] }
derive = { path = "derive" }
actix-web = { version = "4", features = ["rustls"] }
dashmap = { "version" = "6" }
sha3 = "0"
uuid = "1"
config = "0"
validator = "0"
argon2 = { version = "0", features = ["std"] }
deadpool-redis = "0.18.0"

# Useful crates
collection_literals = "1"
colored = "2"
strum = { version = "0", features = ["derive"] }
num_enum = "0"
mockall = "0"
async-trait = { version = "0" }

[dependencies.lettre]
version = "0"
default-features = false
features = ["tokio1", "tokio1-rustls-tls", "smtp-transport", "builder"]

[dev-dependencies]
assert_cmd = "2"
reqwest = "0"
fake = { version = "2" }
linkify = "0"
ctor = "0"
libc-print = "0"
claims = "0"
