[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
anyhow = "1"
serde = { version = "1" }
serde_json = "1"
serde_repr = "0"
tokio-tungstenite = "0"
tungstenite = "0"
sqlx = { version = "0", features = [
    "runtime-tokio",
    "tls-rustls",
    "mysql",
    "macros",
] }
log = "0"
env_logger = "0"
clap = { version = "4", features = ["derive"] }
shadow-rs = "0"
futures-util = "0"
rand = "0"
snowdon = "0"
redis = { version = "0", features = ["tokio-rustls-comp"] }
toml = "0"
sea-orm = { version = "0", features = [
    "sqlx-mysql",
    "runtime-tokio-rustls",
    "macros",
] }
thiserror = "1"
chrono = "0"

[profile.release]
lto = true
codegen-units = 1
strip = true

[build-dependencies]
shadow-rs = "0"

[dev-dependencies]
test_lib = { path = "test_lib" }

[workspace]
members = ["test_lib"]
