cargo-features = ["edition2024"]
[package]
name = "base"
edition.workspace = true
version.workspace = true

[dependencies]
shadow-rs = "0"
validator = "0"
serde = { version = "1" }
anyhow = "1"

[build-dependencies]
shadow-rs = "0"
