[package]
name = "base"
edition.workspace = true
version.workspace = true

[dependencies]
shadow-rs = "0"
validator = "0"
serde = { version = "1" }
anyhow = "1"
chrono = { version = "0", features = ["serde"] }
sha3 = "0"
prost-types = { version = "0" }

[build-dependencies]
shadow-rs = "0"
