# The http server listening ip
ip = "127.0.0.1"
# The http server listening port
port = 7778
rediscfg = "redis.toml"
dbcfg = "database.toml"
# If not set, the email will be disabled
email_cfg = "email.toml"
rabbitmq_cfg = "rabbitmq.toml"
ssl = false
# The logo of this server
logo_path = "../resource/logo.png"
run_migration = false
