[package]
name = "rmodule"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rmodule"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0"
base = { path = "../../../../base" }
