[package]
name = "entities"
version.workspace = true
edition.workspace = true

[dependencies]

[dependencies.sea-orm]
version = "1"
default-features = false
features = ["macros", "with-json", "with-chrono", "with-uuid"]
