[package]
name = "derive"
version.workspace = true
edition.workspace = true

[dependencies]
syn = { version = "2.0", features = ["extra-traits", "full"] }
quote = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true
