name: ci

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  common-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Rust Fmt
        run: cargo fmt --check
      - name: typos-action
        uses: crate-ci/typos@master
        with:
          files: .
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Deps
        run: sudo apt-get update && sudo apt install -y protobuf-compiler
      - name: Flutter Init
        run: cd client/ourchat && flutter pub get
      - name: Grpc generate
        run: python script/generate.pb.dart.py
      - name: Flutter Check
        run: cd client/ourchat && flutter analyze
      - name: FLutter Fmt
        run: cd client/ourchat && dart format ./ --set-exit-if-changed
      - uses: bufbuild/buf-setup-action@v0.3.1
      # Lint
      - uses: bufbuild/buf-lint-action@v0.3.0
      - name: Buf Fmt
        run: buf format --exit-code
