name: ci

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  common-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Rust Fmt
        run: cargo fmt --check
      - name: typos-action
        uses: crate-ci/typos@master
        with:
          files: .
      - name: Flutter Check
        uses: NIOMIND-srl-sb/flutter-analyze-action@v1.0.20
        with:
          token: ${{ secrets.ACTION_TOKEN }}
