name: ci

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  common-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Rust Fmt
        run: cargo fmt --check
      - name: typos-action
        uses: crate-ci/typos@master
        with:
          files: .
      - name: Flutter Init
        run: cd client/OurChat && flutter pub get
      - name: Flutter Check
        run: cd client/OurChat && flutter analyze
      - name: FLutter Fmt
        run: cd client/OurChat && flutter format --set-exit-if-changed .
