name: ci

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Ruff
        run: curl -LsSf https://astral.sh/ruff/install.sh | sh
      - name: Python Fmt
        run: ruff format --check
      - name: Python Lint
        run: ruff check
      - name: Rust Fmt
        run: cargo fmt --check
      - name: typos-action
        uses: crate-ci/typos@master
        with:
          files: .
