name: ci

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  common-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Rust Fmt
        run: cargo fmt --check
      - name: typos-action
        uses: crate-ci/typos@master
        with:
          files: .
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Flutter Init
        run: cd client && flutter pub get
      - name: FLutter Fmt
        run: cd client && dart format ./ --set-exit-if-changed
      - name: Grpc generate
        run: dart pub global activate protoc_plugin && python script/generate.pb.dart.py
      - name: Flutter Check
        run: cd client && flutter analyze
      - uses: bufbuild/buf-setup-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # Lint
      - uses: bufbuild/buf-lint-action@v0.3.0
      - name: Buf Fmt
        run: buf format --exit-code
