name: RustfmtCheck

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check Fmt Server
        run: cd server && cargo fmt -- --check
      - name: Check Fmt Tauri
        run: cd client/src-tauri && cargo fmt -- --check
      - name: Check Fmt Web
        run: cd client/web && cargo fmt -- --check
