name: main_ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  common-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Breaking change detection
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          lint: false
          breaking: true
          format: false
          # The 'main' branch of the GitHub repository that defines the module
          breaking_against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"