name: Nightly Docker Build

on:
  schedule:
    # Run at 00:00 UTC (midnight) every day
    - cron: '0 0 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  check_and_build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for changes
        id: check_changes
        run: |
          git log --since="24 hours ago" --pretty=format:"%h" main | wc -l | xargs -I {} echo "changes={}" >> $GITHUB_OUTPUT

      - name: Set up Python
        if: steps.check_changes.outputs.changes != '0'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up Docker Buildx
        if: steps.check_changes.outputs.changes != '0'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: steps.check_changes.outputs.changes != '0'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker images
        if: steps.check_changes.outputs.changes != '0'
        run: |
          python3 script/build_production_container.py nightly skip_base --push
    