name: ServerMacos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --all
      - name: Sqlite Test
        run: python3 script/test_server.py sqlite
      - name: Build Release
        run: |
          cargo check --all --release
