name: ServerMacos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Up Environment
        run: docker compose -f docker/compose.devenv.yml up -d
      - name: Test
        run: |
          export OURCHAT_TEST_CONFIG_DIR=$(pwd)/config/
          cargo test
      - name: Build
        run: cargo check --all
      - name: Build Release
        run: |
          cargo check --all --release
