name: ServerLinux

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test-Aphine
        run: |
          docker compose -f docker/compose.dev-aphine.yml up -d
          docker compose -f docker/compose.dev-aphine.yml exec OurChatServer sh -c "cd /app && cargo test"
      - name: Test-Debian
        run: |
          docker compose -f docker/compose.dev-debian.yml up -d
          docker compose -f docker/compose.dev-debian.yml exec OurChatServer sh -c "cd /app && cargo test"
