name: ServerMacos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build
        run: cargo check --all
      - name: Build Release
        run: cargo check --all --release
      - name: Test Web
        run: cd client/web/web && cargo test && cargo test --release
      - name: Test Tauri
        run: cd client/src-tauri && cargo test && cargo test --release
