name: ServerMacos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Start Redis
        run: docker run -d -p 6379:6379 redis
      - name: Start RabbitMQ
        run: docker run -d -p 5672:5672 -p 15672:15672 -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=123456 rabbitmq:4-management
      - uses: ikalnytskyi/action-setup-postgres@v7
        with:
          postgres-version: "17"
          password: 123456
      - name: Test
        run: |
          python3 script/action_test_server_macos.py

      - name: Build
        run: cargo build --all
      - name: Build Release
        run: |
          cargo check --all --release
