name: ServerLinux

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Setting Up Valgrind
        run: |
          python3 ./script/init_valgrind_rust.py
          sudo apt update
          sudo apt install valgrind -y
      - name: Build
        run: cargo check --all
      - name: Build Release
        run: cargo check --all --release
      - name: Test
        uses: SkyUOI/github-action-docker-compose-test-run@main
        with:
          file: compose.yml
          service: OurChatServer
          command: "script/action_test_server.py"
          registry: "ghcr.io"
          docker-compose-version: "2.29.1"
          entrypoint: "python3"
