name: RustLinux

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build
        run: cd server && cargo build --all
      - name: Build Release
        run: cd server && cargo build --all --release
      - name: Test
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: docker-compose.yml
          service: OurChatServer
          command: "cd script && python3 action_test_server.py"
          registry: "ghcr.io"
          docker-compose-version: "2.29.1"
