name: ServerMacos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --all
      - name: Set up Docker
        uses: crazy-max/ghaction-setup-docker@v3
      - name: Start Redis
        run: docker run --name win-redis -e REDIS_PORT=6379 -p 6379:6379 -d redis
      - name: Sqlite Test
        run: python3 script/test_server.py sqlite
      - name: Build Release
        run: |
          cargo check --all --release
