name: RustLinux

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Nightly
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
          export MIRIFLAGS="-Zmiri-disable-isolation"
      - name: Setting Up Valgrind
        run: |
          python3 ./script/init_valgrind_rust.py
          sudo apt update
          sudo apt install valgrind -y
      - name: Build
        run: cd server && cargo build --all
      - name: Build Release
        run: cd server && cargo build --all --release
      - name: Test
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: docker-compose.yml
          service: OurChatServer
          command: "cd script && python3 action_test_server.py"
          registry: "ghcr.io"
      # - name: Run miri test
      #   run: cargo miri test
