name: RustWindows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build
        run: cd server && cargo build --all
      - name: Build Release
        run: cd server && cargo build --all --release
      # - name: Run miri test
      #   run: cargo miri test
