name: ServerMacos

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Start Redis
        run: docker run -d -p 6379:6379 redis
      - uses: ikalnytskyi/action-setup-postgres@v7
        with:
          postgres-version: "17"
          password: 123456
      - name: Test
        run: |
          python3 script/test_server.py "cargo test" "config/gh_test/ourchat.toml"

      - name: Build
        run: cargo build --all
      - name: Build Release
        run: |
          cargo check --all --release
