name: ServerCov

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  sqlite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: cargo-bins/cargo-binstall@main
      - name: Tarpaulin
        run: cargo binstall cargo-tarpaulin --no-confirm --force
      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: latest
      - name: Sqlite Test
        run: |
          python3 script/test_server.py sqlite "cargo tarpaulin --bins -o lcov"

      - name: Display Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
