name: ServerCov

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
# Minimum permissions required by skip-duplicate-actions
permissions:
  actions: write
  contents: read

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: "always"
          paths_ignore: '["client/**"]'

  Test:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: cargo-bins/cargo-binstall@main
      - name: Install llvm-cov
        run: cargo binstall cargo-llvm-cov --no-confirm --force
      - name: Install Deps
        run: sudo apt-get update && sudo apt install -y protobuf-compiler
      - name: Set Up Environment
        run: docker compose -f docker/compose.devenv.yml up -d
      - name: Test
        run: |
          export OURCHAT_CONFIG_FILE=$(pwd)/config/
          cargo llvm-cov --lcov --output-path lcov.info

      - name: Display Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          disable_telem: true
          skip_validation: true
