name: ServerCov

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: cargo-bins/cargo-binstall@main
      - name: Tarpaulin
        run: cargo binstall cargo-tarpaulin --no-confirm --force
      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: latest
      - uses: ikalnytskyi/action-setup-postgres@v7
        with:
          postgres-version: "17"
          password: 123456
      - name: Test
        run: |
          python3 script/test_server.py "cargo tarpaulin -e derive --workspace -o lcov" "config/gh_test/ourchat.toml"

      - name: Display Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
